# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: false
google_analytics: 'UA-72671171-2'
title: Saeed Partonia

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bizim Consulting AB

description: SPartonia's Blog
author:
  name: Saeed Partonia
  email: saeed.partonia@gmail.com
  github: spartonia
  twitter: spartonia
  pinterest: false
  linkedin: spartonia
  bio: Software Engineer, with passion in machine learning 
  email_md5: 8d48a70c7d594e734f6d607d0cc85846

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate

permalink: /:title/
